// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjN4s5MJh9dQ8Mxd8_XY-xnFQtFTYJmds',
    appId: '1:877829069369:android:ac46669a9c3210d4dacbe8',
    messagingSenderId: '877829069369',
    projectId: 'abcd-db79b',
    storageBucket: 'abcd-db79b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-wQGqOhX0JxMiKaqqnL_ps4bwdDHpDiM',
    appId: '1:877829069369:ios:1efcce695d630371dacbe8',
    messagingSenderId: '877829069369',
    projectId: 'abcd-db79b',
    storageBucket: 'abcd-db79b.appspot.com',
    androidClientId: '877829069369-oflt7pr45bo11n8p7rtrsijlknfkjgtk.apps.googleusercontent.com',
    iosClientId: '877829069369-uf7qepb3dk09n2sijarbicm70p4hakki.apps.googleusercontent.com',
    iosBundleId: 'com.example.q23',
  );
}
